require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const mongoose = require('mongoose');
const Job = require('../models/Job');

const jobs = [
  // ── TECH COMPANIES ──────────────────────────────────────────────────────
  {
    title: 'Senior Software Engineer', company: 'Google', companyLogo: 'https://logo.clearbit.com/google.com',
    location: 'Bangalore, Karnataka', locationType: 'hybrid', salaryMin: 3000000, salaryMax: 5000000,
    description: 'Build and scale Google-scale systems handling billions of requests. Work on Search, Ads, or Cloud infrastructure.',
    skills: ['Python', 'Go', 'Distributed Systems', 'Kubernetes', 'gRPC', 'SQL', 'Algorithms'],
    experience: '5-8 years', jobType: 'full-time', industry: 'Technology',
    requirements: ['B.Tech/M.Tech CS', '5+ years backend', 'Strong DSA'], applyUrl: 'https://careers.google.com',
    sourcePortal: 'Google Careers',
  },
  {
    title: 'Machine Learning Engineer', company: 'Microsoft', companyLogo: 'https://logo.clearbit.com/microsoft.com',
    location: 'Hyderabad, Telangana', locationType: 'hybrid', salaryMin: 2500000, salaryMax: 4500000,
    description: 'Join Azure AI team to build ML pipelines, train large-scale models, and deploy production AI solutions.',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'Azure ML', 'Docker', 'MLflow', 'SQL'],
    experience: '3-6 years', jobType: 'full-time', industry: 'Technology',
    requirements: ['MS/PhD preferred', 'Strong ML fundamentals', 'Publication record a plus'],
    applyUrl: 'https://careers.microsoft.com', sourcePortal: 'Microsoft Careers',
  },
  {
    title: 'Full Stack Developer', company: 'Zomato', companyLogo: 'https://logo.clearbit.com/zomato.com',
    location: 'Gurugram, Haryana', locationType: 'hybrid', salaryMin: 1800000, salaryMax: 3200000,
    description: 'Build real-time features for Zomato\'s food-tech platform — from order tracking to restaurant dashboards.',
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'Redis', 'GraphQL', 'AWS'],
    experience: '3-5 years', jobType: 'full-time', industry: 'Food Tech',
    requirements: ['3+ years full-stack', 'Experience with high-traffic systems'],
    applyUrl: 'https://www.zomato.com/careers', sourcePortal: 'Zomato Careers',
  },
  {
    title: 'Backend Engineer', company: 'Swiggy', companyLogo: 'https://logo.clearbit.com/swiggy.com',
    location: 'Bangalore, Karnataka', locationType: 'onsite', salaryMin: 1500000, salaryMax: 2800000,
    description: 'Own backend services for Swiggy\'s delivery infrastructure. Build APIs serving 10M+ daily orders.',
    skills: ['Java', 'Spring Boot', 'Kafka', 'MySQL', 'Redis', 'Microservices', 'AWS'],
    experience: '2-5 years', jobType: 'full-time', industry: 'Food Tech',
    requirements: ['Java expertise', 'Distributed systems knowledge', 'Experience with Kafka'],
    applyUrl: 'https://careers.swiggy.com', sourcePortal: 'Swiggy Careers',
  },
  {
    title: 'Data Scientist', company: 'Flipkart', companyLogo: 'https://logo.clearbit.com/flipkart.com',
    location: 'Bangalore, Karnataka', locationType: 'hybrid', salaryMin: 2000000, salaryMax: 3500000,
    description: 'Build recommendation engines, demand forecasting models, and pricing algorithms at e-commerce scale.',
    skills: ['Python', 'R', 'SQL', 'Machine Learning', 'Spark', 'Hive', 'Tableau', 'Statistics'],
    experience: '3-6 years', jobType: 'full-time', industry: 'E-Commerce',
    requirements: ['MS/PhD in quantitative field', 'E-commerce domain experience preferred'],
    applyUrl: 'https://www.flipkartcareers.com', sourcePortal: 'Flipkart Careers',
  },
  {
    title: 'DevOps Engineer', company: 'Infosys', companyLogo: 'https://logo.clearbit.com/infosys.com',
    location: 'Pune, Maharashtra', locationType: 'hybrid', salaryMin: 1200000, salaryMax: 2200000,
    description: 'Manage CI/CD pipelines, cloud infrastructure, and SRE practices for enterprise clients.',
    skills: ['Docker', 'Kubernetes', 'Jenkins', 'Terraform', 'AWS', 'Azure', 'Ansible', 'Python'],
    experience: '3-5 years', jobType: 'full-time', industry: 'IT Services',
    requirements: ['AWS/Azure certified preferred', 'Kubernetes experience mandatory'],
    applyUrl: 'https://www.infosys.com/careers', sourcePortal: 'Infosys Careers',
  },
  {
    title: 'React Native Developer', company: 'Meesho', companyLogo: 'https://logo.clearbit.com/meesho.com',
    location: 'Bangalore, Karnataka', locationType: 'hybrid', salaryMin: 1600000, salaryMax: 2800000,
    description: 'Build and ship mobile features for Meesho\'s social commerce platform reaching 140M+ users.',
    skills: ['React Native', 'JavaScript', 'TypeScript', 'Redux', 'GraphQL', 'REST APIs'],
    experience: '2-4 years', jobType: 'full-time', industry: 'E-Commerce',
    requirements: ['2+ years React Native', 'App store deployment experience'],
    applyUrl: 'https://meesho.io/jobs', sourcePortal: 'Meesho Careers',
  },
  {
    title: 'AI Research Engineer', company: 'Anthropic', companyLogo: 'https://logo.clearbit.com/anthropic.com',
    location: 'Remote', locationType: 'remote', salaryMin: 6000000, salaryMax: 12000000,
    description: 'Work on frontier AI safety research — alignment, interpretability, and Constitutional AI.',
    skills: ['Python', 'PyTorch', 'LLMs', 'Deep Learning', 'Research', 'RLHF', 'Transformers'],
    experience: '5+ years', jobType: 'full-time', industry: 'AI Research',
    requirements: ['PhD preferred', 'Publications in ML/AI', 'Strong math background'],
    applyUrl: 'https://www.anthropic.com/careers', sourcePortal: 'Anthropic Careers',
  },
  {
    title: 'Product Manager', company: 'CRED', companyLogo: 'https://logo.clearbit.com/cred.club',
    location: 'Bangalore, Karnataka', locationType: 'hybrid', salaryMin: 2500000, salaryMax: 4000000,
    description: 'Own the payments and rewards product at CRED. Define strategy, ship fast, and obsess over user experience.',
    skills: ['Product Strategy', 'SQL', 'Analytics', 'User Research', 'Agile', 'A/B Testing'],
    experience: '4-7 years', jobType: 'full-time', industry: 'FinTech',
    requirements: ['MBA preferred', '4+ years PM experience', 'FinTech background a plus'],
    applyUrl: 'https://careers.cred.club', sourcePortal: 'CRED Careers',
  },
  {
    title: 'Cloud Solutions Architect', company: 'TCS', companyLogo: 'https://logo.clearbit.com/tcs.com',
    location: 'Mumbai, Maharashtra', locationType: 'hybrid', salaryMin: 1800000, salaryMax: 3200000,
    description: 'Design cloud migration and modernization solutions for large enterprise clients across BFSI and retail.',
    skills: ['AWS', 'Azure', 'GCP', 'Terraform', 'Architecture', 'Microservices', 'Security'],
    experience: '7-12 years', jobType: 'full-time', industry: 'IT Services',
    requirements: ['Cloud certifications required', '7+ years experience', 'Client-facing skills'],
    applyUrl: 'https://ibegin.tcs.com', sourcePortal: 'TCS iBegin',
  },
  {
    title: 'iOS Developer', company: 'Paytm', companyLogo: 'https://logo.clearbit.com/paytm.com',
    location: 'Noida, UP', locationType: 'hybrid', salaryMin: 1400000, salaryMax: 2500000,
    description: 'Build the Paytm iOS super app — payments, investments, insurance and more in one app used by 300M users.',
    skills: ['Swift', 'Objective-C', 'Xcode', 'Core Data', 'ARKit', 'REST APIs', 'CI/CD'],
    experience: '2-5 years', jobType: 'full-time', industry: 'FinTech',
    requirements: ['Swift expertise', 'App Store published apps', 'Performance optimization skills'],
    applyUrl: 'https://paytm.com/careers', sourcePortal: 'Paytm Careers',
  },
  {
    title: 'Site Reliability Engineer', company: 'Razorpay', companyLogo: 'https://logo.clearbit.com/razorpay.com',
    location: 'Bangalore, Karnataka', locationType: 'hybrid', salaryMin: 2000000, salaryMax: 3500000,
    description: 'Own reliability, observability and incident management for Razorpay\'s payment processing infrastructure.',
    skills: ['Kubernetes', 'Prometheus', 'Grafana', 'Go', 'Python', 'Terraform', 'SRE Practices'],
    experience: '3-6 years', jobType: 'full-time', industry: 'FinTech',
    requirements: ['SRE experience required', 'On-call rotations', '99.99% SLA mindset'],
    applyUrl: 'https://razorpay.com/jobs', sourcePortal: 'Razorpay Careers',
  },
  {
    title: 'Data Engineer', company: 'Wipro', companyLogo: 'https://logo.clearbit.com/wipro.com',
    location: 'Chennai, Tamil Nadu', locationType: 'hybrid', salaryMin: 1000000, salaryMax: 1800000,
    description: 'Build data pipelines and lakehouse architecture for global banking and healthcare clients.',
    skills: ['Apache Spark', 'Hadoop', 'Python', 'SQL', 'Airflow', 'AWS Glue', 'Databricks'],
    experience: '2-5 years', jobType: 'full-time', industry: 'IT Services',
    requirements: ['Data engineering fundamentals', 'SQL expertise', 'Cloud data platform experience'],
    applyUrl: 'https://careers.wipro.com', sourcePortal: 'Wipro Careers',
  },
  {
    title: 'GenAI Product Engineer', company: 'OpenAI', companyLogo: 'https://logo.clearbit.com/openai.com',
    location: 'Remote', locationType: 'remote', salaryMin: 8000000, salaryMax: 15000000,
    description: 'Build next-gen products on top of GPT-4 and beyond. Product-minded engineer who can ship AI experiences.',
    skills: ['Python', 'LLMs', 'OpenAI API', 'React', 'FastAPI', 'Prompt Engineering', 'TypeScript'],
    experience: '4-8 years', jobType: 'full-time', industry: 'AI',
    requirements: ['Strong product sense', 'AI/ML background', 'Shipped production AI products'],
    applyUrl: 'https://openai.com/careers', sourcePortal: 'OpenAI Careers',
  },
  {
    title: 'UI/UX Designer', company: 'Nykaa', companyLogo: 'https://logo.clearbit.com/nykaa.com',
    location: 'Mumbai, Maharashtra', locationType: 'hybrid', salaryMin: 1200000, salaryMax: 2000000,
    description: 'Design beautiful, conversion-optimized experiences for Nykaa\'s beauty e-commerce app with 35M+ users.',
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Usability Testing', 'Adobe XD'],
    experience: '2-4 years', jobType: 'full-time', industry: 'E-Commerce',
    requirements: ['Portfolio required', 'Mobile-first design experience', 'E-commerce background preferred'],
    applyUrl: 'https://www.nykaa.com/careers', sourcePortal: 'Nykaa Careers',
  },
  {
    title: 'Cybersecurity Analyst', company: 'HCL Technologies', companyLogo: 'https://logo.clearbit.com/hcltech.com',
    location: 'Noida, UP', locationType: 'onsite', salaryMin: 900000, salaryMax: 1800000,
    description: 'Perform security assessments, penetration testing, and incident response for global clients.',
    skills: ['SIEM', 'SOC', 'Penetration Testing', 'OWASP', 'Python', 'Firewalls', 'CISSP'],
    experience: '2-5 years', jobType: 'full-time', industry: 'IT Services',
    requirements: ['CEH/CISSP preferred', 'SIEM tools experience', '24/7 SOC experience'],
    applyUrl: 'https://careers.hcltech.com', sourcePortal: 'HCL Careers',
  },
  {
    title: 'Blockchain Developer', company: 'Polygon', companyLogo: 'https://logo.clearbit.com/polygon.technology',
    location: 'Remote', locationType: 'remote', salaryMin: 3000000, salaryMax: 6000000,
    description: 'Build smart contracts, DeFi protocols, and Web3 infrastructure on Polygon\'s Layer 2 network.',
    skills: ['Solidity', 'Ethereum', 'Web3.js', 'Hardhat', 'Rust', 'TypeScript', 'DeFi'],
    experience: '2-5 years', jobType: 'full-time', industry: 'Web3',
    requirements: ['Solidity expertise', 'Smart contract audit experience', 'DeFi protocol knowledge'],
    applyUrl: 'https://polygon.technology/careers', sourcePortal: 'Polygon Careers',
  },
  {
    title: 'Frontend Engineer', company: 'PhonePe', companyLogo: 'https://logo.clearbit.com/phonepe.com',
    location: 'Bangalore, Karnataka', locationType: 'hybrid', salaryMin: 1600000, salaryMax: 2800000,
    description: 'Build lightning-fast React/Next.js frontends for PhonePe\'s payments and financial services platform.',
    skills: ['React', 'Next.js', 'TypeScript', 'CSS', 'Webpack', 'Performance Optimization', 'Jest'],
    experience: '2-5 years', jobType: 'full-time', industry: 'FinTech',
    requirements: ['React expertise', 'Performance-conscious developer', 'Core Web Vitals knowledge'],
    applyUrl: 'https://careers.phonepe.com', sourcePortal: 'PhonePe Careers',
  },
  {
    title: 'Golang Backend Engineer', company: 'Ola', companyLogo: 'https://logo.clearbit.com/olacabs.com',
    location: 'Bangalore, Karnataka', locationType: 'hybrid', salaryMin: 1800000, salaryMax: 3000000,
    description: 'Build Go microservices for Ola\'s ride-matching, surge pricing, and driver optimization platform.',
    skills: ['Go', 'Microservices', 'gRPC', 'Kafka', 'PostgreSQL', 'Redis', 'Docker', 'Kubernetes'],
    experience: '3-6 years', jobType: 'full-time', industry: 'Mobility',
    requirements: ['Go language expertise', 'High-throughput system design', 'Real-time systems experience'],
    applyUrl: 'https://www.olacabs.com/careers', sourcePortal: 'Ola Careers',
  },
  {
    title: 'Technical Program Manager', company: 'Amazon', companyLogo: 'https://logo.clearbit.com/amazon.com',
    location: 'Hyderabad, Telangana', locationType: 'hybrid', salaryMin: 3000000, salaryMax: 5500000,
    description: 'Lead large-scale technical programs across AWS teams. Drive execution, unblock engineers, and own delivery.',
    skills: ['Program Management', 'Technical Architecture', 'Agile', 'Stakeholder Management', 'SQL', 'AWS'],
    experience: '7-12 years', jobType: 'full-time', industry: 'Technology',
    requirements: ['7+ years TPM/PM', 'Engineering background required', 'AWS experience preferred'],
    applyUrl: 'https://amazon.jobs', sourcePortal: 'Amazon Jobs',
  },
  // ── NON-TECH ────────────────────────────────────────────────────────────
  {
    title: 'Growth Marketing Manager', company: 'Zepto', companyLogo: 'https://logo.clearbit.com/zeptonow.com',
    location: 'Mumbai, Maharashtra', locationType: 'hybrid', salaryMin: 1500000, salaryMax: 2500000,
    description: 'Own user acquisition, retention, and CRM strategy for Zepto\'s rapid 10-minute grocery delivery.',
    skills: ['Growth Marketing', 'SQL', 'Google Analytics', 'Meta Ads', 'CRM', 'A/B Testing', 'Retention'],
    experience: '3-6 years', jobType: 'full-time', industry: 'Q-Commerce',
    requirements: ['Growth marketing experience', 'Consumer startup background', 'Data-driven mindset'],
    applyUrl: 'https://www.zeptonow.com/careers', sourcePortal: 'Zepto Careers',
  },
  {
    title: 'Business Analyst', company: 'Deloitte', companyLogo: 'https://logo.clearbit.com/deloitte.com',
    location: 'Mumbai, Maharashtra', locationType: 'hybrid', salaryMin: 1200000, salaryMax: 2200000,
    description: 'Analyze business processes, gather requirements, and deliver digital transformation insights for Fortune 500 clients.',
    skills: ['SQL', 'Excel', 'Power BI', 'Tableau', 'Process Mapping', 'Stakeholder Management', 'Agile'],
    experience: '2-5 years', jobType: 'full-time', industry: 'Consulting',
    requirements: ['MBA preferred', 'Consulting experience', 'Strong analytical skills'],
    applyUrl: 'https://apply.deloitte.com', sourcePortal: 'Deloitte Careers',
  },
  {
    title: 'Content Strategist', company: 'Byju\'s', companyLogo: 'https://logo.clearbit.com/byjus.com',
    location: 'Bangalore, Karnataka', locationType: 'hybrid', salaryMin: 800000, salaryMax: 1500000,
    description: 'Create engaging educational content strategy for K-12 and higher-ed learners across digital platforms.',
    skills: ['Content Strategy', 'SEO', 'Copywriting', 'Analytics', 'Video Scripting', 'EdTech'],
    experience: '2-4 years', jobType: 'full-time', industry: 'EdTech',
    requirements: ['Content writing portfolio', 'EdTech experience preferred', 'SEO knowledge'],
    applyUrl: 'https://byjus.com/careers/', sourcePortal: 'Byju\'s Careers',
  },
  {
    title: 'Financial Analyst', company: 'HDFC Bank', companyLogo: 'https://logo.clearbit.com/hdfcbank.com',
    location: 'Mumbai, Maharashtra', locationType: 'onsite', salaryMin: 900000, salaryMax: 1600000,
    description: 'Perform financial modeling, credit analysis, and investment research for HDFC\'s corporate banking division.',
    skills: ['Financial Modeling', 'Excel', 'Bloomberg', 'Credit Analysis', 'Python', 'CFA Level 1'],
    experience: '2-4 years', jobType: 'full-time', industry: 'Banking',
    requirements: ['CA/MBA Finance', 'Financial modeling skills', 'Banking experience preferred'],
    applyUrl: 'https://www.hdfcbank.com/careers', sourcePortal: 'HDFC Careers',
  },
  {
    title: 'HR Business Partner', company: 'Accenture', companyLogo: 'https://logo.clearbit.com/accenture.com',
    location: 'Pune, Maharashtra', locationType: 'hybrid', salaryMin: 1000000, salaryMax: 1800000,
    description: 'Strategic HR partner supporting tech delivery teams — talent management, culture, and performance programs.',
    skills: ['HR Strategy', 'Talent Management', 'HRBP', 'Workday', 'SuccessFactors', 'Employee Relations'],
    experience: '4-8 years', jobType: 'full-time', industry: 'IT Services',
    requirements: ['MBA HR preferred', 'HRBP experience', 'Tech industry background'],
    applyUrl: 'https://www.accenture.com/in-en/careers', sourcePortal: 'Accenture Careers',
  },
];

const seed = async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  await Job.deleteMany({});
  await Job.insertMany(jobs);
  console.log(`✅ Seeded ${jobs.length} mock jobs`);
  process.exit(0);
};

seed().catch(err => { console.error(err); process.exit(1); });
